config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :followers, only: [:create, :destroy], param: :user_id
  resources :posts do 
    collection do
      get 'explore'
    end
    resource :likes, only: [:create, :destroy], module: :posts
    resources :comments, only: [:show, :create, :new, :destroy], module: :posts
  end
  resources :users, only: [:show], param: :username, path: '' do
    resources :posts, only: [:show], module: :users
  end
  root to: "welcome#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :image, attached: true

  scope :of_followed_users, -> (following_users) { where(user_id: following_users) }

  has_one_attached :image

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  accepts_nested_attributes_for :comments, reject_if: proc { |attributes| attributes['body'].blank? }
end

app/controllers/posts/comments_controller.rb
module Posts
  class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post

    def create
      @comment = @post.comments.build(comments_params.merge(user: current_user))

      if @comment.save
        PostCommentChannel.broadcast_to(@post, comment_created_params)
        #render partial: 'posts/comments/comment', locals: { comment: @comment }
      else
        render partial: 'posts/comments/error', locals: { comment: @comment }, status: :bad_request
      end
    end

    def show
      @comments = @post.comments.where("created_at < ?", DateTime.parse(params[:last_result_timestamp])).order(created_at: :desc).limit(10)
    end

    def destroy
      @comment = @post.comments.find(params[:id])

      #only allow comment-er or post-er to delete comment
      if @comment.user == current_user ||  @post.user == current_user
        @comment.destroy 
        PostCommentChannel.broadcast_to(@post, comment_destroyed_params)
      end
    end

    private

    def comment_created_params
      {action: :created, html: comment_html}
    end

    def comment_destroyed_params
      {action: :destroy, comment_id: @comment.id }
    end

    def comment_html
      # TODO: bug - uses current user of post-er and broadcasts to everyone listening.
      ApplicationController.renderer.render(
        partial: "posts/comments/comment",
        locals: { 
          realtime: true,
          comment: @comment,
          current_user: current_user 
        },
        format: :html
      )
    end

    def more_records?(post, last_result)
      post.comments.where("created_at < ?", last_result.created_at).any?
    end
    helper_method :more_records?
    
    def set_post
      @post = Post.find(params[:post_id])
    end

    def comments_params
      params.require(:comment).permit(:body)
    end

  end
end

app/controllers/posts/likes_controller.rb
module Posts
  class LikesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post

    def create
      @post.likes.where(user: current_user).first_or_create

      respond_to do |format|
        format.html { redirect_to user_post_path(@post.user.username, @post) }
        format.js
      end
    end

    def destroy
      @post.likes.where(user: current_user).destroy_all

      respond_to do |format|
        format.html { redirect_to user_post_path(@post.user.username, @post) }
        format.js
      end
    end

    private
    def set_post
      @post = Post.find(params[:post_id])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.of_followed_users(current_user.following).with_attached_image.order(created_at: :desc)
  end

  def explore
    @posts = Post.with_attached_image.order(created_at: :desc)
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.comments&.first&.user = current_user

    if @post.save
      redirect_to posts_path, notice: "Created Post"
    else
      render :new, notice: "Please try again"
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to user_path(@post.user.username), notice: "Post deleted"
  end

  private 

  def post_params
    params.require(:post).permit(:image, comments_attributes: [:body])
  end
end

app/controllers/users/posts_controller.rb
module Users
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user

    def show
      @post     = @user.posts.with_attached_image.find(params[:id])
      @comments = @post.comments.order(created_at: :desc).limit(10)
      @comment  = @post.comments.new
    end

    private
    def more_records?(post, last_result)
      post.comments.where("created_at < ?", last_result.created_at).any?
    end
    helper_method :more_records?
    
    def set_user
        @user = User.find_by_username!(params[:user_username])
    end
  end
end

app/views/posts/comments/_comment.html.erb
<div class="row mb-3" data-comment-id="comment_<%= comment.id %>">
  <div class="col-sm-1">
    <%= image_tag avatar_url_for(comment.user, size: 48), class:"rounded-circle" %>
  </div>

  <div class="col-sm-11">
    <% unless local_assigns[:realtime].present? %>
      <% if comment.user_id == current_user&.id || comment.commentable.user_id == current_user&.id %>
        <small class="float-right text-muted">
          <%= link_to "Delete", post_comment_path(comment.commentable, comment), method: :delete, remote: true, class: "text-muted", data: { confirm: "Are you sure? This cannot be undone."} %>
        </small>
      <% end %>
    <% end %>

    <small><em><strong>Posted by: <%= comment.user.username %></strong> <%= local_time_ago(comment.created_at) %></em></small>

    <p><%= comment.body %> </p>
  </div>
</div>

app/views/posts/comments/_error.html.erb
<% if comment.errors.any? %>
  <div class="alert alert-danger">
    Please fix the following errors:
    <% comment.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </div>
<% end %>

app/views/posts/comments/_form.html.erb
<div class="my-1">
  <div data-target="comments-list.newCommentErrors"></div>

  <%= form_with(model: [post, comment], html: { data: { type: "html", action: "ajax:success->comments-list#onPostSuccess ajax:error->comments-list#onPostError"}}) do |f| %>
    <%= f.text_area :body, class: "form-control", placeholder: "Say something nice.", data: {target: "comments-list.textarea"} %>
    <div class="mt-3 d-flex justify-content-end">
      <%= f.submit "Post Comment", data: { disable_with: "Posting..." }, class: "btn btn-primary btn-sm rounded" %>
    </div>
  <% end %>
</div>

app/views/posts/comments/_pagination_links.html.erb
<% if last_result.present? && more_records?(post, last_result) %>
  <%= link_to "Load More", post_comment_path(post, last_result_timestamp: last_result.created_at), 
    data: {disable_with: '<div class="spinner-border text-dark" role="status"><span class="sr-only">Loading...</span></div>'}, 
    class: "text-muted underline", remote: true %>
<% end %>

app/views/posts/comments/show.js.erb
var nextPageCommentHTML = "<%= escape_javascript(
  render partial:'posts/comments/comment', collection: @comments.reverse )%>";
var placeholder = document.createElement('div');
placeholder.innerHTML = nextPageCommentHTML;

var updatedPaginationLinksHTML = "<%= escape_javascript(render partial:'posts/comments/pagination_links',
locals:{ post: @post, last_result: @comments.reverse.first }) %>"

var paginationControls = document.querySelector('[data-behavior="pagination-controls"]');
paginationControls.innerHTML = updatedPaginationLinksHTML;
paginationControls.insertAdjacentElement('afterend', placeholder);